### ISSUE TITLE
send_host_app_msg not documented

### ISSUE THREAD

**Issue by Allexin** [MNVolkov/libbip#4]
Не понятно как пользоваться методом для отправки сообщений на телефон.
Как отправлять - понятно. Как на телефоне обрабатывать?

**Comment by MNVolkov** [comment]
Обработкой сообщений в телефоне занимается специальное приложение MiFit, Zepp или Gadget Bridge. Как это реализовано можно посмотреть, например, в исходниках Gadget Bridge.25.03.2021, 02:19, "Allexin" ***@***.***>:
Не понятно как пользоваться методом для отправки сообщений на телефон.
Как отправлять - понятно. Как на телефоне обрабатывать?

**Comment by yuukari** [comment]
> Не понятно как пользоваться методом для отправки сообщений на телефон.
> Как отправлять - понятно. Как на телефоне обрабатывать?

Я как-то написал для этого отдельное приложение, которое интегрируется с Tasker: [https://github.com/Yuukari/BipTask](https://github.com/Yuukari/BipTask). Можете посмотреть еще там исходный код

**Comment by Allexin** [comment]
> Я как-то написал для этого отдельное приложение, которое интегрируется с Tasker: https://github.com/Yuukari/BipTask. Можете посмотреть еще там исходный код

Спасибо. Похоже, ваше приложение в дополнение к BipOS - это то что доктор прописал.
